data:
  val_max_num_images_to_cache: -1
  test_max_num_images_to_cache: -1
  parser:
    class_path: Colmap
    init_args:
      split_mode: "experiment"
model:
  renderer:
    class_path: internal.renderers.gsplat_v1_renderer.GSplatV1Renderer
    init_args:
      absgrad: true
  density:
    densify_grad_threshold: 0.0006
    absgrad: true